baseURL = "http://jscolaire.netlify.com/"
languageCode = "es-ES"
title = "Linux práctico"
theme = "minimal"
#disqusShortname = "username" # delete this to disable disqus comments
#googleAnalytics = ""

[params]
    author = "@jscolaire"
    description = "Blog personal de GNU/Linux y más"
    githubUsername = "jscolaire"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 2

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 3

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:colaire@hotmail.es"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/jscolaire/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/jscolaire/"
    name = "twitter"
    weight = 3

# [[menu.icon]]
#     url = "https://www.linkedin.com/in/username/"
#     name = "linkedin"
#     weight = 4

# [[menu.icon]]
#     url = "https://www.stackoverflow.com/username/"
#     name = "stack-overflow"
#     weight = 5
